### ISSUE TITLE
"Category: uninformed" dans la vue cluster

### ISSUE THREAD

**Issue by frmichel** [Wimmics/ldviz#10]
Dans la vue cluster, quand on survole un auteur on a "Category: uninformed".
Qu'est-ce que cela signifie ? 
Dans quel cas est-ce pertinent ?

**Comment by amenin** [comment]
It was used in the very first version of MGExplorer. The idea was to provide a characteristic information about the node such as the research area of a researcher. However, we haven't included the possibility of providing this information through the query. Thus, I have removed this information from the tooltip, as it does not really exists.
