### ISSUE TITLE
Cluster view: pbs d'affichage des labels des noeuds

### ISSUE THREAD

**Issue by frmichel** [Wimmics/ldviz#14]
1. Les labels des nœuds s'affichent loin de graphe ce qui rend la lecture difficile:
![cluster](https://user-images.githubusercontent.com/1170961/203337259-b2887faf-2cdd-4e18-9260-7671208c1190.jpg)

2. Les labels ne s'affichent que lorsque l'on survole un nœud, il faudrait les afficher en permanence.

3. Lorsque la vue s'ouvre il faut un moyen d'identifier, parmi tous les nœuds, celui sélectionné pour ouvrir la vue, sinon, s'il y en a bcp, on ne sait plus où il est.

**Comment by amenin** [comment]
Fixed !

**Comment by frmichel** [comment]
Je ne vois plus aucun nom :( sur les endpoints ISSA et OpenBiodiv

**Comment by amenin** [comment]
Fixed ! (for real this time)

**Comment by frmichel** [comment]
Top! ;)
