### ISSUE TITLE
Edition de requête: renommer les variables pré-définies des requêtes type

### ISSUE THREAD

**Issue by frmichel** [Wimmics/ldviz#3]
Dans les les requêtes type, les variables pré-définies sont actuellement : ?p = article, ?s et ?o = auteurs. C'est assez "confusant" sachant que, traditionnellement, ?s ?p ?o = subject predicate object. 
L'aide du champ `Institution` parle aussi d'une variable.

Il conviendrait de renommer les variables avec un nom explicite, e.g. 
 ?article, ?author1, ?author1, $institution1 etc.

**Comment by amenin** [comment]
This was actually the initial configuration of the query, when we were only exploring co-authorship. However, as our goal was to support the exploration of any kind of network, we decided to rename the variables and, as we focus on linked data, we chose to follow the traditional names used in the semantic web domain. 
This can be further discussed, but I will leave it like this for now.

**Comment by frmichel** [comment]
Ok, if we want to keep this generic enough, then we should choose variable names like ?node1 ?node2 etc. But definitely not ?s ?p ?o.
