### ISSUE TITLE
Edition de requête: mettre à jour les labels "Query Type"

### ISSUE THREAD

**Issue by frmichel** [Wimmics/ldviz#5]
Dans "Query Type", mettre à jour les labels, e.g. le premier est "Co-authorship within a single institution" alors qu'il n'y a pas d'institution impliquée dans la requête.

**Comment by amenin** [comment]
Finally, the query type was something implemented in the first version of LDViz, which was focused on HAL. With the generalization, it is not used anymore. I removed it from the query editor.
