### ISSUE TITLE
Signification de la taille d'un noeud dans le graphe

### ISSUE THREAD

**Issue by frmichel** [Wimmics/ldviz#9]
Dans le graphe des co-auteurs, la taille d'un nœud est fonction du nombre de connexions. Dans le cas OpenBiodiv, des auteurs ont écrit 1 papier avec 60 auteurs. Donc ces nœuds sont énormes alors qu'ils n'ont qu'un papier. En revanche, un auteur qui a écrit 10 papiers avec 5 co-auteurs est très petit.

Donc ce serait bien d'avoir :
- choisir à quoi correspond la taille du nœud : nombre de connexions ou autre variable retournée par la requête SPARQL
- avoir un code graphique pour représenter la production de l'auteur : un gradient de couleur par exemple, rouge pour les plus prolifiques jqa vert.

**Comment by amenin** [comment]
Dans le Panel de la Graph View, on peut maintenant choisir la variable qui sera représenté par la taille du noeud. Pour l'instant, on peut choisir entre le nombre de co-auteurs et le nombre d'items associé au noeud.

**Comment by frmichel** [comment]
Great!
